### ISSUE TITLE
schema is missing from runner api

### ISSUE THREAD

**Issue by bhou** [ananas-analytics/ananas-desktop#1]
The runner API should return a dataframe in the following format:

```
{
  schema: { fields: []}
  data: [[...], [...]]
  message: optional, the error message if any
}
```

**Comment by ananasjoe** [comment]
curl -X POST \
  'http://localhost:3003/v1/lmj234LKJ4LLMKJ5KJ5JLJ5LJ5LKJ51Hjkjdjhdkh/paginate?page=1&pagesize=3' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'cookie: dmxId=abcdefg' \
  -H 'dnt: 1' \
  -H 'postman-token: 014423df-72d0-e840-66f0-bf88348084da' \
  -H 'referer: http://www.dailymotion.com/' \
  -H 'x-real-ip: 198.54.201.163' \
  -b dmxId=abcdefg \
  -d '{
"type": "Connector",
"config":
{
  "subtype": "file",
  "platform": "local",
  "format": "csv",
  "header": true,
  "path": "/home/grego/Documents/data/score.csv"
}
,
"variables": { }
}'

**Comment by ananasjoe** [comment]
Now we get expected response :
```
{
  "code" : 200,
  "data" : {
    "id" : "lmj234LKJ4LLMKJ5KJ5JLJ5LJ5LKJ51Hjkjdjhdkh",
    "schema" : {
      "fields" : [ {
        "index" : 1,
        "name" : "username",
        "type" : "VARCHAR",
        "userDefined" : false,
        "rowSchema" : null,
        "arrayElementType" : null
      }, {
        "index" : 2,
        "name" : "score",
        "type" : "DOUBLE",
        "userDefined" : false,
        "rowSchema" : null,
        "arrayElementType" : null
      }, {
        "index" : 3,
        "name" : "country",
        "type" : "VARCHAR",
        "userDefined" : false,
        "rowSchema" : null,
        "arrayElementType" : null
      } ]
    },
    "data" : [ [ "bhou", 8.0, "FR" ], [ "gregory", 7.0, "PE" ], [ "bhou", 10.0, "CH" ] ],
    "message" : null
  }
}
```
