### ISSUE TITLE
Support Flink Execution Engine

### ISSUE THREAD

**Issue by ananasjoe** [ananas-analytics/ananas-desktop#20]
As a user I want to run any DAG on a Flink cluster by specifying its URL.

**Comment by ananasjoe** [comment]
Following cluster instructions here :  
https://ci.apache.org/projects/flink/flink-docs-release-1.8/tutorials/local_setup.html#setup-download-and-start-flink

**Comment by bhou** [comment]
Flink is supported as the default local execution engine. Close this one.
