### ISSUE TITLE
Improve date variable input

### ISSUE THREAD

**Issue by bhou** [ananas-analytics/ananas-desktop#59]

**Comment by millboh** [comment]
Basically we need to add an SQL user-defined function that format a date from a string value.

**Comment by millboh** [comment]
Added _todate_ user-defined function that supports optional param 'zoneid' . 

With timezone : 
`SELECT 
ID, 
Joined, 
todate(Joined, 'MMM d, yyyy', 'GMT-2') as mydate
FROM PCOLLECTION`

or without timezone : 
`SELECT 
ID, 
Joined, 
todate(Joined, 'MMM d, yyyy') as mydate
FROM PCOLLECTION`

**Comment by millboh** [comment]
Please review PR https://github.com/ananas-analytics/ananas-desktop/pull/73

**Comment by bhou** [comment]
included in release 0.9.0
