### ISSUE TITLE
analysis of a remote postgres database over putty session

### ISSUE THREAD

**Issue by sahasrara62** [ananas-analytics/ananas-desktop#74]
I have a Postgres database in server, I am connecting it with putty, and putty is binding the port of the server and my system in the terminal, then from the terminal, i am able to log in the database and then make process on it. 
since it is a binding port, i don't need to give the url of the database and it will directly take over control over there
is there a way to do this in this tool?

**Comment by millboh** [comment]
I'm not sure what is your SSH Putty configuration. If you are using REMOTE FORWARDING you can simply put localhost in the Postgresql URL as **localhost* and the binded port : 
postgresql://localhost:<binded_port>/<your database>
We can use it with any SSL tunnelling tool .

**Comment by sahasrara62** [comment]
i am using the same way, but unable to get the data, is there any way/method that checks the connection if the connection to the database is set up or not?

**Comment by bhou** [comment]
If there is a connection issue, you will see an error message when exploring the data source. What kind of error did you see?

**Comment by sahasrara62** [comment]
@bhou  let me tell you this on tuesday, i can't remember the error, but i was not able to see the result in tool(i wa first time using the tool, iwthout reading mannual), i like to say if there is feature which check if connection establish with db then it would be really great. :D
