### ISSUE TITLE
MongoDB support?

### ISSUE THREAD

**Issue by qqilihq** [ananas-analytics/ananas-desktop#76]
Hi,

despite the readme says, that MongoDB is supported, I couldn’t find any MongoDB component in v0.8.2 (macOS). I've found some (commented) configuration in the repo. Could you give a quick heads up regarding MongoDB support?

Beside that: This looks really promising -- I'll keep an eye on the project!

Offtopic: Is there some plugin or extension concept which would allow to develop custom components?

**Comment by bhou** [comment]
0.8.x is our first public release, to make our support a bit easier, we removed several features from the prototype, for example, excel, MongoDB, plain text log, javascript, etc. We are now working on version 0.9 to put some of these features back. MongoDB is in the 0.9.0 roadmap.

In term of the plugin, we don't have a hot load plugin system like Eclipse, or Visual Studio Code for now. Currently, we do make lots of efforts to make the customization easier:

- Step UI customization: you can customize the step editor by editing a YAML file without touching the js code
- New Step (Source, transform, destination or visualization): you can add a class extends our abstract step types. There are lots of examples in the code base, which might give you a hint. 

Any PR is welcomed!

I will make a how-to contribution guide in the wiki later to introduce the details.

**Comment by qqilihq** [comment]
Thank you very much for the feedback! I'll be really looking forward to see a plugin system -- I’m currently working with [KNIME](http://knime.com), and the plugin interface and the huge node ecosystem is a killer feature (I've also developed several node extensions for KNIME, especially for web scraping and information extraction, see [here](https://nodepit.com/product/palladian) and [here](https://seleniumnodes.com)).

I'll definitely keep watching this project, and can  well imagine contributing extensions once there's an API. Ananas’ foundation definitely looks more fresh and modern than the Eclipse-based KNIME platform.

Keep up the good work!

**Comment by millboh** [comment]
Thanks @qqilihq . We are working on mongodb and plugin in 0.10.0 version.

**Comment by qqilihq** [comment]
Awesome! Looking forward and fingers crossed!

**Comment by bhou** [comment]
Support in 0.10.0. Close this one.
